### ISSUE TITLE
Intermittent failure running playbook

### ISSUE THREAD

**Issue by jacobstr** [bcwaldon/klondike#19]
Occasionally, when trying to update farva manually via the bastion instance I see:

```
TASK [kubelet : upload cluster CA certificate] *********************************
fatal: [***]: FAILED! => {"failed": true, "msg": "ERROR! failed to resolve remote temporary directory from ansible-tmp-1463680630.15-264393012566816: `( umask 22 && mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1463680630.15-264393012566816 )\" && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1463680630.15-264393012566816 )\" )` returned empty string"}
```

Doing these sort of out-of-band updates is generally not the approach you should be using when interacting with the klondike core components, but I'm concerned this might happen during a normal deployment.

Repeating `ansible-playbook -e cluster=bulbasaur -l tag_group_gateway site.yml` tends to work.

**Comment by bcwaldon** [comment]
Project moved to github.com/planetlabs/klondike
